@baseUrl = http://localhost:8000/


GET {{baseUrl}}/posts/
Content-Type: application/json
Authorization: Token 98e99a80bd41a9c4f95f562a91c740d6880a0264

###

# добавление лайка
POST {{baseUrl}}/posts/1/like/
Content-Type: application/json
Authorization: Token 98e99a80bd41a9c4f95f562a91c740d6880a0264


###

# удаление поста
DELETE {{baseUrl}}/posts/2/
Content-Type: application/json
Authorization: Token 98e99a80bd41a9c4f95f562a91c740d6880a0264


###


# изменение текста поста
PATCH {{baseUrl}}/posts/2/
Content-Type: application/json
Authorization: Token 98e99a80bd41a9c4f95f562a91c740d6880a0264

{
  "text": "second post"
}


###

# добавление комментария
POST {{baseUrl}}/posts/1/comment/
Content-Type: application/json
Authorization: Token 98e99a80bd41a9c4f95f562a91c740d6880a0264

{
  "text": "new comment"
}

###


# изменение текста комментария
PATCH {{baseUrl}}/posts/1/comment/3
Content-Type: application/json
Authorization: Token 98e99a80bd41a9c4f95f562a91c740d6880a0264

{
  "text": "changed comment"
}


###


# удаление комментария
DELETE {{baseUrl}}/posts/1/comment/4
Content-Type: application/json
Authorization: Token 98e99a80bd41a9c4f95f562a91c740d6880a0264


###


# фильтрация по создателю
GET {{baseUrl}}/posts/?creator=1
Content-Type: application/json


###


# фильтрация по дате
GET {{baseUrl}}/posts/?created_at_before=2025-01-22
Content-Type: application/json
